name: Generate Snake

# Trigger the action every 6 hours and allow manual trigger
on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Generate the snake GIF using Platane's action
    - name: Generate Snake GIF
      uses: Platane/snk@master
      id: snake-gif
      with:
        github_user_name: mishmanners
        gif_out_path: dist/github-contribution-grid-snake.gif
        svg_out_path: dist/github-contribution-grid-snake.svg

    # Step 3: Show the status of the build
    - name: Show git status
      run: git status

    # Step 4: Commit and push changes to the output branch
    - name: Commit and push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: output
        force: true

    # Step 5: Deploy to GitHub Pages (optional)
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
